spark.sql.extensions                            org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions,org.projectnessie.spark.extensions.NessieSparkSessionExtensions
spark.sql.catalog.iceberg                       org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.iceberg.catalog-impl         org.apache.iceberg.nessie.NessieCatalog
spark.sql.catalog.iceberg.uri                  http://nessie:19120/api/v2
spark.sql.catalog.iceberg.ref                  main
spark.sql.catalog.iceberg.authentication.type  NONE
spark.sql.catalog.iceberg.warehouse            s3a://iceberg-warehouse/
spark.hadoop.fs.s3a.endpoint                    http://minio1:9000
spark.hadoop.fs.s3a.access.key                  minioadmin
spark.hadoop.fs.s3a.secret.key                  minioadmin123
spark.hadoop.fs.s3a.path.style.access           true
spark.hadoop.fs.s3a.connection.ssl.enabled      false
spark.hadoop.fs.s3a.impl                        org.apache.hadoop.fs.s3a.S3AFileSystem
